[[redirects]]
  from = "/capoeira/curso-especializacao"
  to = "https://tonhaodev.notion.site/2026-Capoeira-Curso-de-Especializa-o-Tarefas-3e97ef11c4558092b6f6ca384d9db2d7?source=copy_link"
  status = 301
  force = true
